### PR TITLE
example distilling problem found in #80

### PR DESCRIPTION
**Pull request by boneskull**
I was able to reproduce my problem after modifying the tests you created.

This PR is not intended to be merged, but wanted to show you what I'm seeing.

summary:

1. Add `esm` as a dev dep
1. Rewrite `A`, `B` and `C` modules to use ESM syntax instead of `module.exports`
1. Copy & split `test.spec.js` into two files, `test-a.spec.js` and `test-b.spec.js`

After pulling this PR down, run `npm install`, then run `npm run test:80`.  This will execute Mocha with `test-a.spec.js`, then another time with `test-b.spec.js` (both of which pass), then finally `test.spec.js`, which will fail.

### CODE REVIEW

**Comment by theKashey** [comment]
Got it. So it's somehow related to `esm`

**Comment by boneskull** [comment]
yeah ... :/  

I think @jdalton would probably be willing to address this if we can narrow it down a bit.

**Comment by boneskull** [comment]
If rewiremock is using strict equality to compare modules somewhere, this may fail, because `esm` wraps target `Module`s in `Proxy` objects.  So, the original `Module` won't be strictly equal to the esm-ified version.  I reported a problem like this with [Unexpected](https://github.com/unexpectedjs/unexpected/issues/631), which they solved with [this change](https://github.com/unexpectedjs/unexpected/pull/633).

**Comment by boneskull** [comment]
`proxyquire` does *not* seem to exhibit this behavior, if that helps.

**Comment by theKashey** [comment]
Long story short - I've run all rewiremock tests using `esm` and there is a cache clearance problem.

**Comment by theKashey** [comment]
Add one more test, in the middle
```js
  it('mock C', () => {
    const subject = rewiremock.proxy(
      () => require('./A'),
      () => {
        rewiremock(() => require('./C'))
          .with('bar')
      }
    );
    expect(subject.default).to.be.equal('bar')
  });
```

It would fail, but the last one - would pass :)

**Pull request merged**
