### PR TITLE
Fix missing Flow type information for rewiremock/node

### LINKED ISSUE #101: Missing Flow type information for rewiremock/node
When importing from `rewiremock/node`, the type information for Flow is missing.

Using this as a current workaround:

```
// @flow
import rewiremock from 'rewiremock/node'
import typeof RewireMock from 'rewiremock'

// Setup...

export default (rewiremock: RewireMock)
```

### PR DESCRIPTION
**Pull request by langri-sha**
Fixes #101 

Adds Flow pragma to `rewiremock/node`. Tested with `flow type-at-pos node.js 11 37`

### CODE REVIEW

**Comment by langri-sha** [comment]
Please let me know if you would prefer adding `node.js.flow` instead.

**Comment by theKashey** [comment]
Wow! Is it enought?

**Comment by langri-sha** [comment]
Yes! I tested with `flow type-at-pos node.js 11 37`, the type there is `rewiremock` :+1:!

**Comment by theKashey** [comment]
👍 , I'll release a new version today.

**Comment by theKashey** [comment]
Released `3.13.8`

**Comment by langri-sha** [comment]
Thank you :bowing_man:!

**Pull request merged**
